# Generated by Django 5.0.2 on 2024-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageforroadmap',
            name='titel',
        ),
    ]
