# Generated by Django 5.0.2 on 2024-03-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_remove_imageforroadmap_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforroadmap',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='imageforroadmap',
            name='subpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmaps.subpage'),
        ),
    ]
