# Generated by Django 5.0.2 on 2024-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_blog_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
